CREATE TABLE IF NOT EXISTS article (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(255),
    category VARCHAR(255) NOT NULL,
    author VARCHAR(500),
    title VARCHAR(500) NOT NULL,
    description VARCHAR(500),
    url VARCHAR(500) NOT NULL UNIQUE,
    published_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_article_category ON article(category);